# Generated by Django 6.0.7 on 2026-07-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('salary', models.CharField(max_length=100)),
                ('roadmap', models.TextField()),
                ('resources', models.TextField()),
            ],
        ),
    ]
