# Generated by Django 6.0.7 on 2026-07-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='opportunities',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='quiz_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='career',
            name='resources_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='career',
            name='roadmap_link',
            field=models.URLField(blank=True),
        ),
    ]
